# Generated by Django 4.2.5 on 2023-10-20 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('total_calories', models.CharField(max_length=30)),
                ('meals_per_day', models.IntegerField(default=3)),
                ('meals_per_week', models.IntegerField(default=6)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Y', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='menu_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('calories', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Y', max_length=1)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Y', max_length=1)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu_items')),
            ],
        ),
    ]
