# Generated by Django 4.2.5 on 2023-11-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menu_items_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meals_per_day',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meals_per_week',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='total_calories',
        ),
        migrations.AddField(
            model_name='menu',
            name='daily_plan_price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='menu',
            name='monthly_plan_price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='menu',
            name='weekly_plan_price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bundle',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.bundle_type'),
        ),
    ]
