# Generated by Django 4.2.5 on 2023-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_orders_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
