# Generated by Django 4.2.5 on 2023-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_users_image_remove_users_username_users_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='activity_level',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='height_in',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='heignt_feet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='weight_goal',
            field=models.FloatField(null=True),
        ),
    ]
