# Generated by Django 4.2.5 on 2023-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_details_weight_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='heignt_feet',
            new_name='height_feet',
        ),
    ]
