# Generated by Django 4.2.5 on 2023-10-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurants'),
        ),
    ]
